version: '3.3'

networks:
  monitoring:
    driver: bridge 
    
volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    expose:
      - 9090   
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    #volumes:
    #  - grafana_data:/var/lib/grafana
    #  - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    #  - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false        
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - monitoring
    
  sample-client:
    build:
      context: ./
      dockerfile: Dockerfile-client
    container_name: sample-client 
    command:
      - "/app/async-client.py"
    ports:
     - "8000:8000"
    expose:
      - 8000
    networks:
      - monitoring
